language: clojure
script: lein spec
sudo: false
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_deploy:
  - lein ring uberjar
  - export RELEASE_PKG_FILE=$(ls target/*standalone.jar)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key: "Ezk8tsFDXZTckQRLZNrds++Kk41Ewx4yyNKLCksi/NLMDLIC9WMFNLu6qcgK7eZZnXxqVaDe8c3fhg2DMer40Dp25Lrt7l78S++0R6kPANacC/lJSChhkr/STRRVDuIKGW6PeSlOgdXpCojQ78k93ll9UhuZcmdLGXGYAZojOgBQQW8tbZ/HGQz41ZQbhaLx/OwEPjhGYu8oDz7OhzgYybftBsjMhKX3CeH1ur7hqOcZuqzDcQzfYcmHGunBvUD084SbNAm7XEKinX34etj9Oy+N9dSa83lUGB81LxgjGZm9N6NFG0DwF3z3/mb/H7twFzLgv5HBEAq+B8ZH2InaNaCvzVxjdJZcss358L7Hd+lTK4q7UeFid7vR/nEcDj5Wjyf09rf/Qw0wJRoVoZVr3JDLS5qbBuhfYcOvd901VO49hrRrCfCFCMN5pj746OLfNv/GiEggB2O/AS/eXWOgK+BRGyEODTgrqyGXbLllNd9BpR9kbMEHqlrlbbbNUA43Z4RZDeOTNLeBQqFuOjy1dFeLANqw9ePL3ZlxpsxEQ9oc6BImzvEuADiRuoqP0qhawv0d8wQKX2Ztm3S8nkX0Vk7hm2KocMVKmbeRp9y/s43pY6EOX3OafmXYzWmCnrK+rMx3zTsVPZ4ClOU0mZ0klJrWR0FXCbIuLwhzdRD7K/Y="
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
