language: clojure
script: lein spec
sudo: false
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_deploy:
  - lein ring uberjar
  - export RELEASE_PKG_FILE=$(ls target/*standalone.jar)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key: "v2C0ndIYxXH1y2yKFNmRkujLv+6PkVmw19OrdSbOfNQpMnEWVCYARZxxuev+5ygU4NsTlesp5ZmRsMAFY4xkRqo0WkHyYPqzGscRB6XasxT7TJArUt+2NrxpgiHX4dglD7qIbL98JuWWoTOduDtnu5ZzegeXKKCqb2DY1/gU2TGpfZv/FE8GVz6xnG/tJf5lysJctpd1yEZyy7ZgdirtA52pyIqAF+XKexCGbPKLTILylq+C9Pf4PRULm6coQuGVWQdTr+mHvozQLz/uUrLXJonrTnSplnt59xy7R1uc10J9tkae2Qc4vutcVNQQd6AmauGnXOd2tfc1ZsXfHRJuqRjdLFLF3hwajg14oP3JMKkvxc57e5RsqnIh6tkahRT7q6ji1Bt0D1fn51WucCbpTYuzLJZf4AzH99dlJXe1NyQy7gfMYENysJt2DnTzP8CEfpeQSFktpMcNXhthI9eCiDKvRSjxgGHM8gZAYpwMgZOkWc3J6HnpkWUU18isd+NjhCdMG8bN/1/B5GTTVHfveQ5fjETYyn0MWDxnxB+IfiSbidzkWi25DW40w2YY0EES8+UMuz/IUyhOdIuDZpWysa3oPXt8I3trsNuBGVL1rnpQ/jF3VAX+OJ1o4gImkSFkdt9GN4nYSolvZNwbtQRwoZPgW7eDtYkY66KNXL5sFEI="
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
