language: clojure
script: lein spec
sudo: false
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

before_deploy:
  - lein ring uberjar
  - export RELEASE_PKG_FILE=$(ls target/*standalone.jar)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key: "WHttUdfDcXIBfJ43WUce1DfGQYmoRM1DuVpGNHS4F83vcXEXQYX66MVL2ydHMwrqYfAkRbEehLA8Lu7twqO9GNrmnWdZGHCDVylRtambGQHpj06vxu+unPOp2Bf/bS/aivfTXSjHKzVVQwlNArUnBCTTHkG6eCSyFLIvdFKSZAbMyhK21kaLt9ht5BPgn2Oesl2jfaC91rU0uzXe+XWsiItu8/w4Gcr9NNIkqeOXSqU1bIIBuWsgGqGoZA3WW8/YMqMiy4Vw/f2anfZHTd71TxgT1h0MLw+wnoj4HtUqsIMsg35K+NtHzbfvOKlf/Ot6+NxH0J0dHPQJ+Xvi48GQSrGDeg6wJ0/UPhJSe1Ws4+KkZN+dJpXOcrw0JO3zqlEFQ3lBe5GW7/YGxHW6xWjlNJ6sxmN23734axXi6KHtvmtUjvYD6mDDfYXU9UU3noNRq6pFheBXF0B0/l6DHYdMsidymWK7yyt3BtdVZuWcH3cSN0MUT1RH85ApBN7P8743iwWfpXuCxsTBvKbnkqXlsG2cIdk0KxiY729tovxlKPanRE4PKqtp56obzlg1XcFiBVn8xXEgtmwL9SPLZ/v+sGniRwc9TuyB6TUAgDUjb/+FAxg856eb2gR3n8ASlLBQOSrtMaGKxYArDRbUDmfMj7hIyjNENb5E/WYdBKBuLXs="
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
